import { Router, type Router as RouterType } from "express";
import health from "./health.js";
import settings from "./settings.js";
import providers from "./providers.js";
import chat from "./chat.js";
import threads from "./threads.js";
import skills from "./skills.js";
import memories from "./memories.js";
import people from "./people.js";
import tasks from "./tasks.js";
import plugins from "./plugins.js";
import mcp from "./mcp.js";
import usage from "./usage.js";
import exportImport from "./export.js";

import models from "./models.js";
import voices from "./voices.js";
import image from "./image.js";
import heartbeat from "./heartbeat.js";
import cron from "./cron.js";
import workspaces from "./workspaces.js";
import update from "./update.js";
import dm from "./dm.js";
import messages from "./messages.js";
import sing from "./sing.js";
import emotion from "./emotion.js";
import browser from "./browser.js";
import agents from "./agents.js";

const router: RouterType = Router();

router.use(health);
router.use(settings);
router.use(providers);
router.use(chat);
router.use(threads);
router.use(skills);
router.use(memories);
router.use(people);
router.use(tasks);
router.use(plugins);
router.use(mcp);
router.use(usage);
router.use(exportImport);

router.use(models);
router.use(voices);
router.use(image);
router.use(heartbeat);
router.use(cron);
router.use(workspaces);
router.use(update);
router.use(dm);
router.use(messages);
router.use(sing);
router.use(emotion);
router.use(browser);
router.use(agents);

export default router;
